# frozen_string_literal: true

module InquiryAttrs
  # Manages the lifecycle of the inquiry_attrs initializer inside a Rails app.
  #
  # This class holds all file-system logic so it can be unit-tested without
  # requiring a full Rails boot or Rake DSL.  The rake tasks are thin shells
  # that delegate here.
  #
  # @example From a Rake task (or Rails generator):
  #   InquiryAttrs::Installer.install!(Rails.root)
  #   InquiryAttrs::Installer.uninstall!(Rails.root)
  #
  class Installer
    INITIALIZER_PATH = Pathname.new('config/initializers/inquiry_attrs.rb')

    INITIALIZER_CONTENT = <<~RUBY
      # frozen_string_literal: true

      # Auto-include InquiryAttrs::Concern into every ActiveRecord model so that
      # the .inquirer macro is available without an explicit include in each class.
      #
      # Generated by: rails inquiry_attrs:install
      #
      # To opt out of auto-include, remove this file and add
      #   include InquiryAttrs::Concern
      # to whichever models need it.
      ActiveSupport.on_load(:active_record) do
        include InquiryAttrs::Concern
      end
    RUBY

    # Write the initializer to +rails_root/config/initializers/inquiry_attrs.rb+.
    #
    # @param rails_root [Pathname, String] the root directory of the Rails app
    # @return [:created, :skipped]
    def self.install!(rails_root)
      destination = Pathname.new(rails_root).join(INITIALIZER_PATH)

      return :skipped if destination.exist?

      destination.write(INITIALIZER_CONTENT)
      :created
    end

    # Remove the initializer if it exists.
    #
    # @param rails_root [Pathname, String]
    # @return [:removed, :skipped]
    def self.uninstall!(rails_root)
      destination = Pathname.new(rails_root).join(INITIALIZER_PATH)

      return :skipped unless destination.exist?

      destination.delete
      :removed
    end
  end
end
